### ISSUE TITLE
whitespace in the latest container sig file

### ISSUE THREAD

**Issue by richardlehane** [digital-preservation/pronom#8]
Hi @Dclipsham 
hope this is the right place to report this. 

Just working on signature updates for sf and I noticed in testing I was getting failures for fmt/936 and fmt/646. I checked and droid also is failing ID for these files with the latest container signatures. 

Both failures appear to relate to line-wrapping whitespace. Because both of these signatures are quoted strings ('bla') - sf and droid take the new whitespace as literally part of the signature.

cheers
Richard

**Comment by Dclipsham** [comment]
Thanks Richard, I can replicate. I'll publish a new container signature over the next day or two to correct this. 

David

**Comment by Dclipsham** [comment]
Hi Richard,

I've released the new container signature and internal testing suggests the problem is resolved. Could you please re-test?

David

**Comment by richardlehane** [comment]
brilliant, thanks very much David. Just successfully built a new signature file. 
cheers
Richard
